"""baseline

Revision ID: 1ca8aba92fd3
Revises: 
Create Date: 2026-05-25 19:24:15.463757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8aba92fd3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankcashflowexclusionrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pluggy_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pattern_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankcashflowexclusionrule_direction'), 'bankcashflowexclusionrule', ['direction'], unique=False)
    op.create_index(op.f('ix_bankcashflowexclusionrule_pattern_normalized'), 'bankcashflowexclusionrule', ['pattern_normalized'], unique=False)
    op.create_index(op.f('ix_bankcashflowexclusionrule_pluggy_category'), 'bankcashflowexclusionrule', ['pluggy_category'], unique=False)
    op.create_table('bankincomeexclusionrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pluggy_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pattern_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankincomeexclusionrule_pattern_normalized'), 'bankincomeexclusionrule', ['pattern_normalized'], unique=False)
    op.create_index(op.f('ix_bankincomeexclusionrule_pluggy_category'), 'bankincomeexclusionrule', ['pluggy_category'], unique=False)
    op.create_table('bankincomemonth',
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('income_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year_month')
    )
    op.create_index(op.f('ix_bankincomemonth_year_month'), 'bankincomemonth', ['year_month'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('creditcardinvoicemonth',
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('payment_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year_month')
    )
    op.create_index(op.f('ix_creditcardinvoicemonth_year_month'), 'creditcardinvoicemonth', ['year_month'], unique=False)
    op.create_table('ignoreddescriptionrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ignoreddescriptionrule_pattern_normalized'), 'ignoreddescriptionrule', ['pattern_normalized'], unique=True)
    op.create_table('item',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('connector_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('sync_finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthlybalancemonth',
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('income', sa.Numeric(), nullable=False),
    sa.Column('card_spend', sa.Numeric(), nullable=False),
    sa.Column('invoice_paid', sa.Numeric(), nullable=False),
    sa.Column('net_by_purchase_month', sa.Numeric(), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(), nullable=False),
    sa.Column('income_count', sa.Integer(), nullable=False),
    sa.Column('card_spend_count', sa.Integer(), nullable=False),
    sa.Column('invoice_payment_count', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('year_month')
    )
    op.create_index(op.f('ix_monthlybalancemonth_year_month'), 'monthlybalancemonth', ['year_month'], unique=False)
    op.create_table('account',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('marketing_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_item_id'), 'account', ['item_id'], unique=False)
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('monthly_target', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_category_id'), 'budget', ['category_id'], unique=True)
    op.create_table('budgetoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_target', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'year_month', name='uq_budgetoverride_month')
    )
    op.create_index(op.f('ix_budgetoverride_category_id'), 'budgetoverride', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgetoverride_year_month'), 'budgetoverride', ['year_month'], unique=False)
    op.create_table('categoryrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pluggy_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoryrule_category_id'), 'categoryrule', ['category_id'], unique=False)
    op.create_index(op.f('ix_categoryrule_pluggy_category'), 'categoryrule', ['pluggy_category'], unique=True)
    op.create_table('descriptioncategoryrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pattern_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descriptioncategoryrule_category_id'), 'descriptioncategoryrule', ['category_id'], unique=False)
    op.create_index(op.f('ix_descriptioncategoryrule_pattern_normalized'), 'descriptioncategoryrule', ['pattern_normalized'], unique=True)
    op.create_table('accountsync',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_transaction_date', sa.Date(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('transaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('accountsync')
    op.drop_index(op.f('ix_descriptioncategoryrule_pattern_normalized'), table_name='descriptioncategoryrule')
    op.drop_index(op.f('ix_descriptioncategoryrule_category_id'), table_name='descriptioncategoryrule')
    op.drop_table('descriptioncategoryrule')
    op.drop_index(op.f('ix_categoryrule_pluggy_category'), table_name='categoryrule')
    op.drop_index(op.f('ix_categoryrule_category_id'), table_name='categoryrule')
    op.drop_table('categoryrule')
    op.drop_index(op.f('ix_budgetoverride_year_month'), table_name='budgetoverride')
    op.drop_index(op.f('ix_budgetoverride_category_id'), table_name='budgetoverride')
    op.drop_table('budgetoverride')
    op.drop_index(op.f('ix_budget_category_id'), table_name='budget')
    op.drop_table('budget')
    op.drop_index(op.f('ix_account_item_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_monthlybalancemonth_year_month'), table_name='monthlybalancemonth')
    op.drop_table('monthlybalancemonth')
    op.drop_table('item')
    op.drop_index(op.f('ix_ignoreddescriptionrule_pattern_normalized'), table_name='ignoreddescriptionrule')
    op.drop_table('ignoreddescriptionrule')
    op.drop_index(op.f('ix_creditcardinvoicemonth_year_month'), table_name='creditcardinvoicemonth')
    op.drop_table('creditcardinvoicemonth')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_bankincomemonth_year_month'), table_name='bankincomemonth')
    op.drop_table('bankincomemonth')
    op.drop_index(op.f('ix_bankincomeexclusionrule_pluggy_category'), table_name='bankincomeexclusionrule')
    op.drop_index(op.f('ix_bankincomeexclusionrule_pattern_normalized'), table_name='bankincomeexclusionrule')
    op.drop_table('bankincomeexclusionrule')
    op.drop_index(op.f('ix_bankcashflowexclusionrule_pluggy_category'), table_name='bankcashflowexclusionrule')
    op.drop_index(op.f('ix_bankcashflowexclusionrule_pattern_normalized'), table_name='bankcashflowexclusionrule')
    op.drop_index(op.f('ix_bankcashflowexclusionrule_direction'), table_name='bankcashflowexclusionrule')
    op.drop_table('bankcashflowexclusionrule')
    # ### end Alembic commands ###
