"""expected_income_override

Revision ID: fadace8cdbc2
Revises: 70c5ff02b465
Create Date: 2026-05-26 10:48:40.267198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fadace8cdbc2'
down_revision: Union[str, Sequence[str], None] = '70c5ff02b465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expectedincomeoverride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expected_income_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['expected_income_id'], ['expectedincome.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expected_income_id', 'year_month', name='uq_expectedincomeoverride_entry_month')
    )
    op.create_index(op.f('ix_expectedincomeoverride_expected_income_id'), 'expectedincomeoverride', ['expected_income_id'], unique=False)
    op.create_index(op.f('ix_expectedincomeoverride_year_month'), 'expectedincomeoverride', ['year_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expectedincomeoverride_year_month'), table_name='expectedincomeoverride')
    op.drop_index(op.f('ix_expectedincomeoverride_expected_income_id'), table_name='expectedincomeoverride')
    op.drop_table('expectedincomeoverride')
    # ### end Alembic commands ###
